### ISSUE TITLE
GWalkR PKG: How to change the UI BKG from Black to White in the Rstudio [ Viewer ] Pane?

### ISSUE THREAD

**Issue by sfd99** [Kanaries/GWalkR#10]
**Hi Kanaries,**

Thanks for the GWalkR pkg!
_Very helpful._

**Q** 
    How to change  the UI BKG color
     from Black to White in the Rstudio [ Viewer ] Pane?
(the UI bkg is Black right now...).

_Thanks!_
 **sfd99
San Francisco
 - GWalkR version 0.1.2
 - Rstudio v 2023.06.0 Build 421
 - Ubuntu Linux 20.04
 ======================**

**Comment by bruceyyu** [comment]
@sfd99 Hi there thanks for using GWalkR! Right now, it doesn't support customization of the UI background color, so it follows your system setting. We will support this parameter in our next version.
If you need to make it white now, I think the easiest way is to set the whole system appearance to "light" mode.

**Comment by sfd99** [comment]
Understood.
Thanks, Bruce!.
Really like it.

BTW:
once you start 
a new [ Chart ] tab in the UI,
how to **close** a Chart tab ?.
(say you have
 2 or 3 different Chart Tabs 
 currently open in the Viewer...).

**Comment by bruceyyu** [comment]
> BTW: once you start a new [ Chart ] tab in the UI, how to **close** a Chart tab ?. (say you have 2 or 3 different Chart Tabs currently open in the Viewer...).

That's a feature to be supported in graphic-walker, the core library of GWalkR. Great suggestion! I have created an issue there https://github.com/Kanaries/graphic-walker/issues/155 and other team members will handle it.

**Comment by bruceyyu** [comment]
@sfd99 The dark mode customization has been supported in v0.1.3, so I will close this issue and open another issue #12 for the chart tab deletion

For the latest version please refer to https://cran.r-project.org/web/packages/GWalkR/index.html
