### ISSUE TITLE
How to close GWalkR session which started in Rstudio?

### ISSUE THREAD

**Issue by wzrzt** [Kanaries/GWalkR#14]
I started GWalkR in Rstudio. It is really good. But I find I can't close it. After one day I can still visit GwalkR in my browser. And I'm using Rstudio to explore many datasets, I can't restart my Rstudio.

**Comment by bruceyyu** [comment]
@wzrzt If you use GWalkR in the "Viewer" tab of the R Studio, you should be able to clear the view using the buttons at the upper left corner.
<img width="284" alt="image" src="https://github.com/Kanaries/GWalkR/assets/33870780/af84128b-68ca-4bbf-9659-8c3b506f43be">

**Comment by wzrzt** [comment]
So, will the "clear" kill GWalkerR background process?

**Comment by bruceyyu** [comment]
> So, will the "clear" kill GWalkerR background process?

@wzrzt I think so, and the histories will all be gone
