### ISSUE TITLE
It's empty in the "Viewer" panel of RStudio, and can only open in local website

### ISSUE THREAD

**Issue by liangpingding** [Kanaries/GWalkR#15]
<img width="722" alt="Screenshot 2023-11-07 at 21 55 54" src="https://github.com/Kanaries/GWalkR/assets/29528469/9703a9e1-de48-4a1b-bfa2-c13984d45f31">

**Comment by bruceyyu** [comment]
@possible1402 Hi it's hard to reproduce your issue but I found some packages using htmlwidgets also cannot work in some versions of RStudio https://github.com/rstudio/rstudio/issues/6737
Can you please take a look at your environment and RStudio version, and if it's possible, upgrade the RStudio?

**Comment by liangpingding** [comment]
Thanks for your solution! I updated the RStudio version and problem solved!
