### ISSUE TITLE
GWalkr bug

### ISSUE THREAD

**Issue by trafficfan** [Kanaries/GWalkR#17]
! [image](https://github.com/Kanaries/GWalkR/assets/149685680/4e60d37e-f49c-4e1e-bbb3-188491fdc93c)
 New version of RStudio can't open GWalkr scripts, RGui can

**Comment by bruceyyu** [comment]
I tried after updating my RStudio to version 2024.04.1+748 on my Mac, but it seems to work fine. May I know the exact versions of your device and software?

BTW, I found a similar issue here, can you please maybe download the patch? @trafficfan 
https://github.com/rstudio/rstudio/issues/14603

**Comment by trafficfan** [comment]
After using the patch the problem was solved, thanks!
