### ISSUE TITLE
File not found error in Firefox

### ISSUE THREAD

**Issue by bill-raynor** [Kanaries/GWalkR#19]
Firefox on Debian running R 4.4.1.
```
install.packages("GWalkr")
library(GWalkR) 
data(iris)
gwalkr(iris)`

```
gives "File Not Found" error in Firefox.
If I `cd` to the listed directory and  try `open index.html` the terminal  I get 
`Gtk-Message: 19:13:21.253: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
`
followed by the same file not found error in Firefox. 
How do I fix that?

**Comment by bruceyyu** [comment]
@bill-raynor sorry to hear that. Unfortunately I haven’t tested the package in linux environment. Did you open it in RStudio or command line? I highly recommend using GWalkR in RStudio

**Comment by bill-raynor** [comment]
Thank you, I was using the command line. it works fine from RStudio.
